apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default  

  destination:
    namespace: default
    server: https://kubernetes.default.svc

  source:
    repoURL: https://github.com/devops-dojo/nginx-k8s.git
    targetRevision: HEAD
    path: manifests

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
